### ISSUE TITLE
Electron shouldn't go behind solder

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#77]
Discovered in #76, the electron is sometimes layered incorrectly after connection
![image](https://user-images.githubusercontent.com/679486/28292244-732fa8aa-6b0b-11e7-9e54-cd1b88ce6cb4.png)

**Comment by samreid** [comment]
I committed a proposed fix.  Will be ready for review in next published version.

**Comment by samreid** [comment]
Ready for testing in this version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.85/circuit-construction-kit-dc_en.html

@arouinfar can you please test this and related behaviors?

**Comment by phet-steele** [comment]
@samreid @arouinfar, I see a mixture of electrons going in front of or behind verticies. Not exactly the same thing, I know, but is it at all problematic?

![image](https://user-images.githubusercontent.com/5863899/28444104-e0175e86-6d77-11e7-9ac0-f613113ec12d.png)

This is in  http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html.

**Comment by phet-steele** [comment]
On that note, in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html, I still see electrons behind solder when in schematic view.

At least three cases (probably more):

1. In schematic view, drag out a wire.
2. Then, drag out either a battery, resistor, or switch and connect it directly to the wire. DO NOT place the components into the play area before connecting.

![image](https://user-images.githubusercontent.com/5863899/28444166-758e6536-6d78-11e7-9476-c9ced384f65e.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/26.

**Comment by arouinfar** [comment]
Thanks for reviewing @phet-steele. I would prefer for the layering to be consistent across the vertices and the lifelike/schematic views. Definitely not important for AAPT, but should be addressed for 1.0. Back to you @samreid.

**Comment by samreid** [comment]
It may be simplest to put all charges in front of all circuit elements (still behind light bulb sockets and series ammeter front panels).  However, this would mean that when wires overlap, the electrons are not occluded by the frontmost wire.  But it would simplify the code somewhat and improve performance a bit.  I was hesitant to try this before because I wanted the effect of electrons going "under" other overlapping wires, but now that electrons are transparent this may be no big deal.

I'll probably try this out soon, but co-assigning to @ariel-phet and @arouinfar for feedback on the proposal--sound OK?

**Comment by samreid** [comment]
Here's a depiction of the layering problem I mentioned-- in the previous version the wire electrons went behind the battery.  After this change they go in front:

![image](https://user-images.githubusercontent.com/679486/28491235-a402bc54-6eaa-11e7-907d-94025991200e.png)

@arouinfar and @ariel-phet is this acceptable or should we keep searching for solutions that occlude electrons sometimes?  At one point @Denz1994 and I considered is moving the charges to the circuit element for layering, but that would put them behind the solder for wires so I don't think that will work.

**Comment by samreid** [comment]
Here's a "poor man's change set" in case we want to pursue the idea above:

![image](https://user-images.githubusercontent.com/679486/28491263-5db62b5e-6eab-11e7-8a15-478a28931eea.png)

**Comment by arouinfar** [comment]
@samreid the screenshot in https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-317182108 looks fine to me, and I think the electron opacity helps a bit.

**Comment by samreid** [comment]
@arouinfar can you please review the last UPDATE in https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-317180996 ?

**Comment by arouinfar** [comment]
>  I forgot the proposal fails to address the socket case where electrons are supposed to be in front of the socket sometimes. @arouinfar and @ariel-phet is this a critical feature?

@samreid can you clarify? The electrons in the associated screenshot look fine to me.

**Comment by samreid** [comment]
In master, the charge on the right hand side of the bulb is in front (to indicate it is on the outer part of the socket):

![image](https://user-images.githubusercontent.com/679486/28531251-7f9e635e-7053-11e7-8395-20bccd4eb385.png)

**Comment by arouinfar** [comment]
Thanks @samreid. Given that the advantages of the proposed changes (simplified code, improved performance, more consistent layering) I could live with the behavior shown in https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-317462282. I think @ariel-phet should also review and advise, though.

**Comment by samreid** [comment]
I realized that if the electrons didn't overlap in the socket, we might be able to address this problem by creatively cutting the socket image--taking a "bite" out of the top right corner, sending that to the back layer and leaving it out of the front layer.  That might make it so the electrons always go in front of it without needing to be relayered?  If this look is important https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-317462282 this proposed workaround may be worth it so that we can simplify the layering with respect to charges.

**Comment by ariel-phet** [comment]
@samreid @arouinfar the current layering in master looks good to me.

**Comment by samreid** [comment]
> @samreid @arouinfar the current layering in master looks good to me.

Master has the following issues:
1. Charges sometimes go behind solder, like https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-316866918
2. Changing layers when electrons go from one circuit element to another is a costly scenery action, leading to increased CPU, memory usage and garbage collection.
3. Changing layers leads to increased code complexity and leaves more opportunities for bugs to lurk

I could investigate other solutions to these problems, but one possible solution is to put all charges in a single charge layer.  However, that leads to the undesirable behavior depicted in https://github.com/phetsims/circuit-construction-kit-dc/issues/77#issuecomment-317182108 where electrons from an obscured component are not obscured.  If that is too buggy-looking, then I can investigate other ways to ensure the solder is always behind the electrons (1), but we'll still be left with (2) and (3). 

What do you recommend?

**Comment by samreid** [comment]
Note to self, meters and circuit elements currently share a layer, so moving electrons in front of circuit elements means electrons will be in front of the meters (unless we change something).

**Comment by samreid** [comment]
I moved all electrons to a dedicated layer and published 2 version for review:

bulb sockets in front of electrons
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.107/circuit-construction-kit-dc_en.html

electrons in front of bulb sockets:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.108/circuit-construction-kit-dc_en.html

If we like this strategy of keeping all electrons in a dedicated layer, but still want electrons on the right hand side of the light bulb to go over while electrons at the bottom vertex go "through" the socket, it will take another 4-8 hours or so.

**Comment by arouinfar** [comment]
@samreid @ariel-phet I find the electrons going over the bulb to be a bit jarring, so I prefer dev.107. The layering in dev.108 makes me think the electrons are traveling on top of the glass, rather than through the filament. However, I suppose I could argue the same about the electrons traveling on the insulating layer around the resistor, rather than through it... so maybe in time I would get used to layering the electrons on top of everything.

The electrons in dev.107 have a bit of a strange transition from the right vertex to the filament, but I don't find it to be problematic. If we decide to go with dev.107, I don't think we need to create special-case layering for the right vs. bottom of the socket as @samreid.
![image](https://user-images.githubusercontent.com/8419308/28597907-ae393ddc-715d-11e7-9f69-70139fac6c5b.png)

**Comment by ariel-phet** [comment]
@arouinfar @samreid there is a part of me that definitely likes the consistency of the electrons always being "on top" - especially now that they are semi-transparent, it seems like they are representing the flow of current in general. It seems we are putting lots of effort into the lightbulb case where in other cases (such as the resistor as @arouinfar pointed out) the electrons are not going through the insulating layer.

It seems much of the effort is to match the Java version. Are we really that concerned about the learning goal of "this part of the socket is metal, this is insulator, this is where current goes"? It strikes me as a major simplification to just put the electrons on top, and it seems to then make all components consistent. We should certainly talk with @kathy-phet but I am leaning towards this approach, as it seems to have advantages for simplification/and potentially performance.

**Comment by samreid** [comment]
dev.107 and dev.108 would have approximately the same performance since both have a dedicated electron layer.  It could simplify the light bulb code a little bit (probably 20 lines of code) to always have electrons on top of the socket.  My initial reaction to seeing the "south" and "east" electrons in front of the socket was it looked like there should be a short circuit from one vertex to the other.  However, I am biased from being used to seeing it the other way and it may be OK with students and teachers.

**Comment by ariel-phet** [comment]
@samreid than in that case lets go with dev.107 approach. We certainly have had lots of feedback on Java CCK over the years, and nobody ever complained about the electron layering, so I guess that is good data in addition to you and @arouinfar preferring that style. The short circuiting look is also a good point.

**Comment by kathy-phet** [comment]
I'm not sure what all components this is impacting, but for the case of the light bulb I think we would be impacting student understanding. We know it goes down through the center, but I don't know that all the students who use this sim would make that assumption and I could imagine a lot of teachers having trouble with representing the electrons on the outside of the bulb at that point. Other options could be creating a cut away look there when the electrons are visible. K

Sent from my iPhone

On Jul 25, 2017, at 8:10 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@arouinfar<https://github.com/arouinfar> @samreid<https://github.com/samreid> there is a part of me that definitely likes the consistency of the electrons always being "on top" - especially now that they are semi-transparent, it seems like they are representing the flow of current in general. It seems we are putting lots of effort into the lightbulb case where in other cases (such as the resistor as @arouinfar<https://github.com/arouinfar> pointed out) the electrons are not going through the insulating layer.

It seems much of the effort is to match the Java version. Are we really that concerned about the learning goal of "this part of the socket is metal, this is insulator, this is where current goes"? It strikes me as a major simplification to just put the electrons on top, and it seems to then make all components consistent. We should certainly talk with @kathy-phet<https://github.com/kathy-phet> but I am leaning towards this approach, as it seems to have advantages for simplification/and potentially performance.

**Comment by kathy-phet** [comment]
Sorry, seems like you all already settled on having same flow.  Hadn't seen those emails. K

Sent from my iPhone

On Jul 26, 2017, at 7:24 AM, Kathy Perkins <katherine.perkins@Colorado.EDU<mailto:katherine.perkins@Colorado.EDU>> wrote:

I'm not sure what all components this is impacting, but for the case of the light bulb I think we would be impacting student understanding. We know it goes down through the center, but I don't know that all the students who use this sim would make that assumption and I could imagine a lot of teachers having trouble with representing the electrons on the outside of the bulb at that point. Other options could be creating a cut away look there when the electrons are visible. K

Sent from my iPhone

On Jul 25, 2017, at 8:10 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@arouinfar<https://github.com/arouinfar> @samreid<https://github.com/samreid> there is a part of me that definitely likes the consistency of the electrons always being "on top" - especially now that they are semi-transparent, it seems like they are representing the flow of current in general. It seems we are putting lots of effort into the lightbulb case where in other cases (such as the resistor as @arouinfar<https://github.com/arouinfar> pointed out) the electrons are not going through the insulating layer.

It seems much of the effort is to match the Java version. Are we really that concerned about the learning goal of "this part of the socket is metal, this is insulator, this is where current goes"? It strikes me as a major simplification to just put the electrons on top, and it seems to then make all components consistent. We should certainly talk with @kathy-phet<https://github.com/kathy-phet> but I am leaning towards this approach, as it seems to have advantages for simplification/and potentially performance.

**Comment by samreid** [comment]
This issue has resolved the problem of electrons going behind the solder and we agreed the bulb socket should be in front.  I'll create another issue to make sure we are on the same page about the "east" electron in the socket.
